const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const filmRouter = require('./filmRouter')
const genreRouter = require('./genreRouter')
const formatRouter = require('./formatRouter')
const personRouter = require('./personRouter')
const positionRouter = require('./positionRouter')
const nominationRouter = require('./nominationRouter')
const awardRouter = require('./awardRouter')

router.use('/user', userRouter)
router.use('/film', filmRouter)
router.use('/genre', genreRouter)
router.use('/format', formatRouter)
router.use('/person', personRouter)
router.use('/position', positionRouter)
router.use('/nomination', nominationRouter)
router.use('/award', awardRouter)

module.exports = router