const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const filmRouter = require('./filmRouter')
const genreRouter = require('./genreRouter')
const formatRouter = require('./formatRouter')
const facesRouter = require('./facesRouter')
const positionRouter = require('./positionRouter')
const nominationsRouter = require('./nominationsRouter')
const awardsRouter = require('./awardsRouter')

router.use('/user', userRouter)
router.use('/film', filmRouter)
router.use('/genre', genreRouter)
router.use('/format', formatRouter)
router.use('/faces', facesRouter)
router.use('/position', positionRouter)
router.use('/nominations', nominationsRouter)
router.use('/awards', awardsRouter)

module.exports = router